# Generated by Django 4.0.4 on 2022-07-20 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_reciperequirement_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperequirement',
            name='unit',
        ),
    ]
