# Generated by Django 4.0.4 on 2022-07-29 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_reciperequirement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem'),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient'),
        ),
    ]
